python ./retrain.py^
 --image_dir ./Images^
 --learning_rate=0.0005^
 --testing_percentage=20^
 --validation_percentage=20^
 --train_batch_size=32^
 --validation_batch_size=-1^
 --flip_left_right True^
 --random_scale=30^
 --random_brightness=30^
 --eval_step_interval=100^
 --how_many_training_steps=600^
 --architecture mobilenet_1.0_224^
 --output_graph retrained_graph.pb^
 --output_labels retrained_labels.txt